apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nordic-lights
spec:
  selector:
    matchLabels:
      name: nordic-lights
  template:
    metadata:
      labels:
        name: nordic-lights
    spec:
      containers:
      - name: sensor-data-reader
        image: ghcr.io/true-north-engineering/nordic-lights:0.1
        volumeMounts:
        - name: config-volume
          mountPath: /work/config
        - name: sensor-data-volume
          mountPath: /tmp/dht11_sensor_data
      volumes:
      - name: config-volume
        configMap:
          name: nordic-lights
      - name: sensor-data-volume
        hostPath:
          path: /tmp/dht11_sensor_data
          type: File
